PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6

STATUS_OPEN = "open"
STATUS_CLOSED = "closed"
STATUS_CHOICES = [(STATUS_OPEN, "Open"), (STATUS_CLOSED, "Closed")]

STATUS_DISPLAY_CHOICES = [
    (STATUS_OPEN, "Открыт"),
    (STATUS_CLOSED, "Закрыт"),
]

GITHUB_DOMAIN = "github.com"

PROJECTS_PER_PAGE = 12
USERS_PER_PAGE = 12
