services:
  db:
    image: postgres:16
    container_name: teamfinder_db
    environment:
      POSTGRES_DB: team_finder
      POSTGRES_USER: team_finder
      POSTGRES_PASSWORD: team_finder
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
