import re

NAME_MAX_LENGTH = 124
SURNAME_MAX_LENGTH = 124
PHONE_MAX_LENGTH = 12
ABOUT_MAX_LENGTH = 256

PHONE_REGEX = re.compile(r"^(8\d{10}|\+7\d{10})$")

GITHUB_DOMAIN = "github.com"

PASSWORD_LABEL = "Пароль"
EMAIL_LABEL = "Email"
NAME_LABEL = "Имя"
SURNAME_LABEL = "Фамилия"

FILTER_OWNERS_OF_FAVORITES = "owners-of-favorite-projects"
FILTER_OWNERS_OF_PARTICIPATING = "owners-of-participating-projects"
FILTER_INTERESTED_IN_MINE = "interested-in-my-projects"
FILTER_PARTICIPANTS_OF_MINE = "participants-of-my-projects"

AVATAR_SIZE = 128
FONT_SIZE = 60
FONT_COLOR = (255, 255, 255)

FONT_PATH_MAC = "/System/Library/Fonts/Helvetica.ttc"
FONT_PATH_LINUX = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

COLOR_CORNFLOWER_BLUE = (100, 149, 237)
COLOR_STEEL_BLUE = (119, 158, 203)
COLOR_CADET_BLUE = (95, 158, 160)
COLOR_DARK_SEA_GREEN = (143, 188, 143)
COLOR_LIGHT_STEEL_BLUE = (176, 196, 222)
COLOR_LIGHT_SKY_BLUE = (135, 206, 250)
COLOR_MEDIUM_PURPLE = (147, 112, 219)
COLOR_ROSY_BROWN = (188, 143, 143)
COLOR_BURLYWOOD = (210, 180, 140)
COLOR_PALE_GREEN = (152, 251, 152)

AVATAR_COLORS = [
    COLOR_CORNFLOWER_BLUE,
    COLOR_STEEL_BLUE,
    COLOR_CADET_BLUE,
    COLOR_DARK_SEA_GREEN,
    COLOR_LIGHT_STEEL_BLUE,
    COLOR_LIGHT_SKY_BLUE,
    COLOR_MEDIUM_PURPLE,
    COLOR_ROSY_BROWN,
    COLOR_BURLYWOOD,
    COLOR_PALE_GREEN,
]
